######################################################################
# Automatically generated by qmake (3.0) Tue Mar 29 16:46:02 2022
######################################################################

TEMPLATE = app
TARGET = sailjailtest
INCLUDEPATH += .
CONFIG += sailfishapp

# Input
SOURCES += sailjailtest.cpp
